const imagePath = (fileName) =>
  fileName ? `${process.env.PUBLIC_URL}/images/${fileName.normalize("NFD")}` : "";

export const categories = [
  { id: "all", name: "전체" },
  { id: "youtube", name: "유튜브영상" },
  { id: "corporate", name: "기업영상" },
  { id: "interview", name: "인터뷰영상" },
  { id: "etc", name: "그 외" },
];

export const works = [
  {
    id: "hana-alley",
    title: "하나금융그룹 & 골목기행 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=NyC8BVUjrBQ&t=44s",
    imageSrc: imagePath("골목기행썸네일.png"),
  },
  {
    id: "earnestmeal",
    title: "어니스트밀",
    category: "그 외",
    link: "https://youtu.be/mZ-vdUDYpp8",
    imageSrc: imagePath("어니스트밀.png"),
  },
  {
    id: "hyundai-kia",
    title: "",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=Bz85OdiRQKw",
    imageSrc: imagePath("현대기아연구소.png"),
  },
  {
    id: "hana-bank-interview",
    title: "하나은행 & 인터뷰영상 ",
    category: "인터뷰영상",
    link: "https://www.youtube.com/watch?v=aNTIfFd8UCg",
    imageSrc: imagePath("하나은행영업추진략회의.png"),
  },
  {
    id: "mental-health-concert",
    title: "보건복지부 & 정신건강힐링콘서트 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=fjK3mjHGo48&t=1970s",
    imageSrc: imagePath("정신건강힐링콘서트 썸네일.png"),
  },
  {
    id: "national-pt",
    title: "내셔널 PT센터 홍보영상",
    category: "그 외",
    link: "https://youtu.be/yBd1WxsQS5U",
    imageSrc: imagePath("내셔널pt센터.png"),
  },
  {
    id: "puruni",
    title: "푸르님보육지원재단 & 어린이집 영상 & 홍보영상",
    category: "그 외",
    link: "https://youtu.be/shnTp6_WY_o",
    imageSrc: imagePath("푸르니보육지원재단썸네일.png"),
  },
  {
    id: "good-consumption",
    title: "하나금융그룹 & 착한소비 챌린지 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=l8gfMS_IX_U",
    imageSrc: imagePath("착한소비챌린지썸네일03.png"),
  },
  {
    id: "fishing-village",
    title: "귀어귀촌종합지원센터",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=ZSaLCzwCKpo",
    imageSrc: imagePath("경기도귀어귀촌.png"),
  },
  {
    id: "faceline",
    title: "성형외과유튜브",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=fnOgR1eFDZg&t=185s",
    imageSrc: imagePath("페이스라인.png"),
  },
  {
    id: "healiv",
    title: "피부과유튜브",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=y38S-Eg2QQY",
    imageSrc: imagePath("힐리브의원썸네일.png"),
  },
  {
    id: "health-prescription",
    title: "한국건강보험심사평가원 & 건강처방전 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=szaAHitmGZ8&t=202s",
    imageSrc: imagePath("건강처방전썸네일.png"),
  },
  {
    id: "kogas-opening",
    title: "한국가스공사 & 오프닝영상 & 기업영상",
    category: "기업영상",
    link: "https://www.youtube.com/watch?v=vBuCnceGaj0",
    imageSrc: imagePath("한국가스공사 썸네일.png"),
  },
  {
    id: "hana-gold-shop",
    title: "하나금융그룹 & 금은방 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=MsK4UpPl5FU",
    imageSrc: imagePath("금은방썸네일.png"),
  },
  {
    id: "hana-new-vision",
    title: "하나금융그룹 & 뉴비전공감워크샵 & 기업영상",
    category: "기업영상",
    link: "https://youtu.be/Le_ac1RZnLM",
    imageSrc: imagePath("뉴비전공감워크샵썸네일.png"),
  },
  {
    id: "hana-awards",
    title: "하나금융그룹 & 시상식영상 & 기업영상",
    category: "기업영상",
    link: "https://youtu.be/n63cHcICKs0",
    imageSrc: imagePath("벤처시상식썸네일02.png"),
  },
  {
    id: "dementia-center",
    title: "중앙치매센터 & 행사영상",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=X6WWZPgZi0A",
    imageSrc: imagePath("중앙치매센터 썸네일.png"),
  },
  {
    id: "hana-on",
    title: "하나은행 & 실적영상 & 기업영상",
    category: "기업영상",
    link: "https://www.youtube.com/watch?v=I1wf1FKuBug",
    imageSrc: imagePath("하나온.png"),
  },
  {
    id: "kogas-interview",
    title: "한국가스공사 & 인터뷰영상",
    category: "인터뷰영상",
    link: "https://www.youtube.com/watch?v=ABBkiSDdnRE",
    imageSrc: imagePath("한국가스공사 인터뷰 썸네일.png"),
  },
  {
    id: "hana-golf",
    title: "하나금융그룹 & 골프대회스케치 &유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=IFWi5dgsK-g&t=61s",
    imageSrc: imagePath("골프현장스케치썸네일.png"),
  },
  {
    id: "hana-promotion",
    title: "하나금융그룹 & 기업홍보영상",
    category: "기업영상",
    link: "https://youtu.be/l69sVQ-iM7M",
    imageSrc: imagePath("영업추진회의 썸네일.png"),
  },
  {
    id: "hana-performance",
    title: "하나금융그룹 & 기업성과홍보영상",
    category: "기업영상",
    link: "https://www.youtube.com/watch?v=mZiope0ujws",
    imageSrc: imagePath("자산관리썸네일.png"),
  },
  {
    id: "class101",
    title: "101클라스 & 소개영상",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=3NUqfGSGs0M",
    imageSrc: imagePath("클라스101.png"),
  },
  {
    id: "najeon",
    title: "나전칠기 & 인터뷰영상",
    category: "인터뷰영상",
    link: "https://youtu.be/EC0jdok29aU",
    imageSrc: imagePath("나전칠기 썸네일.png"),
  },
  {
    id: "youth-finance-education",
    title: "청소년금융교육협의회 & 자립준비청년 금융교육 & 유튜브 교육 영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=bjwIEgLU2Ho&t=102s",
    imageSrc: imagePath("자립준비청년 썸네일03.png"),
  },
  {
    id: "hana-object-theater",
    title: "하나금융그룹 & 사물극장 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=7s7ns27BEHQ",
    imageSrc: imagePath("사물극장썸네일.png"),
  },
  {
    id: "hana-choir",
    title: "하나금융그룹 & 합창영상 & 기업영상",
    category: "기업영상",
    link: "https://youtu.be/A6HofoiO59Y",
    imageSrc: imagePath("하나은행합창.png"),
  },
  {
    id: "hana-allowance",
    title: "하나금융그룹 & 슬기로운 용돈생활 & 드라마타입 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=b_QSGeihvs8&t=137s",
    imageSrc: imagePath("슬기로운 용돈생활 썸네일.png"),
  },
  {
    id: "hana-bromantic-comedy",
    title: "하나금융그룹 & 브로맨틱코미디 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=JXOW0cdp8GI&t=93s",
    imageSrc: imagePath("브로맨틱코미디썸네일.png"),
  },
  {
    id: "youth-finance-sketch",
    title: "청소년금융교육협의회 & 스케치영상",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=b31Ta3rLyIs",
    imageSrc: imagePath("자립준비청년스케치썸네일.png"),
  },
  {
    id: "hana-ontact",
    title: "하나금융그룹 & 온택트캠페인 & 유튜브영상",
    category: "유튜브영상",
    link: "https://www.youtube.com/watch?v=vqdioz21PCA&t=88s",
    imageSrc: imagePath("온택트캠페인 썸네일.png"),
  },
  {
    id: "youth-foundation-donation",
    title: "청소년그루터기재단 & 기부 독려영상 & 홍보영상 ",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=1n9iZo9gRhk",
    imageSrc: imagePath("청소년그루터기 기부독려 썸네일.png"),
  },
  {
    id: "cinematic-vlog",
    title: "씨네마틱 브이로그 영상",
    category: "그 외",
    link: "https://www.youtube.com/watch?v=OfAiJgMtjHY",
    imageSrc: imagePath("씨네마틱브이로그.png"),
  },
  {
    id: "hana-job",
    title: "하나금융그룹 & 직무소개영상 & 기업영상",
    category: "기업영상",
    link: "https://www.youtube.com/watch?v=9473c7ROuIY",
    imageSrc: imagePath("pb직무소개영상.png"),
  },
  {
    id: "hana-family-volunteer",
    title: "하나금융그룹 & 가족사랑봉사단 & 기업영상",
    category: "기업영상",
    link: "https://www.youtube.com/watch?v=9473c7ROuIY",
    imageSrc: imagePath("가족사랑봉사단썸네일.png"),
  },
];
